### ISSUE TITLE
General-question: Service-Worker results to old CSS when updating.

### ISSUE THREAD

**Issue by pmochine** [rishabh3112/gridsome-plugin-pwa#41]
Sorry, I don't know really where to ask this question except for here.

When I upload a new build to my server, and I visit for example `https://example.com/imprint`, the result is that the CSS is missing, since the CSS file got a newly generated hash name but the service-worker returns the old HTML build with the old CSS hash name.

The only solution is to refresh with "shift+cmd+4", to delete all cache and to restart the service worker. Obviously, this is not what normal users would do. 

How can I fix this? Any idea? 🙈

Here is a short gif for you to see the problem in action

![philippmoch2](https://user-images.githubusercontent.com/25006691/84028910-d4935980-a991-11ea-8aaa-8d2c0658e79c.gif)

At the very last second, I'm hard-refreshing the page and only then I see the correct imprint page.

**Comment by rishabh3112** [comment]
You may want to update to latest version of the plugin.
Issue is resolved and my site https://rishabhchawla.now.sh/ uses latest and don't face such issues anymore.

**Comment by pmochine** [comment]
Ok I resolved the bug. Under Application go to "Clear storaage" and clear the whole site. Only then it works!

**Comment by pmochine** [comment]
Update: Unfortunately, the problem is back and I'm not even sure :(

**Comment by dikaio** [comment]
@pmochine if you server allows you to do so you should try disabling cache for your service-workers.js files. I believe that should fix your issues.

**Comment by pmochine** [comment]
@dikaio Thank you for your time and your comment. I appreciate it.

Here is my nginx settings. But this should be fine as well right?

    #Disable cache in service-worker
    location = /service-worker.js {
        add_header Cache-Control "public, max-age=0, must-revalidate";
    }
